# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install pipenv
          command: pip install pipenv

      - run:
          name: Setup project
          command: make setup

      - run:
          name: Run tests
          command: make test

      - run:
          name: Generate coverage html report
          command: pipenv run coverage html -d test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
